services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-store-app
    ports:
      - "8282:8282"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped
